"""Reusable ImGui widgets for building MyoGestic ``@app.ui`` functions."""

from myogestic.widgets.common import panel_header
from myogestic.widgets.control_map_editor import ControlMapEditor
from myogestic.widgets.panels import (
    BUILTIN_FILTERS,
    AppLogo,
    FilterParam,
    FilterProcessor,
    FilterSpec,
    Image,
    LogPanel,
    PostProcessor,
    ProcessLauncher,
    RecordButton,
    RecordingControls,
    StreamManager,
    popout_panel,
)
from myogestic.widgets.plots import Heatmap, LinePlot, Scatter2D, Scatter3D
from myogestic.widgets.pong import PongTask
from myogestic.widgets.signals import (
    DEFAULT_DEVICES,
    LSL_DEVICE,
    OTB_DEVICES,
    SYNTHETIC_DEVICE,
    DeviceOption,
    DeviceParam,
    DevicePicker,
    DeviceSpec,
    RawSignalViewer,
    SignalViewer,
    StreamPanel,
)
from myogestic.widgets.tracking import TrackingTask
from myogestic.widgets.training import (
    FeatureSelector,
    PredictionLabel,
    SessionManager,
    TemplateInspector,
    TemplateInspectorRow,
    TrialPreview,
)
from myogestic.widgets.vhi import (
    VhiMovementPanel,
    VhiStateCache,
    VhiStateSnapshot,
    request_vhi_state_refresh,
    vhi_movement_palette,
)

__all__ = [
    "BUILTIN_FILTERS",
    "DEFAULT_DEVICES",
    "LSL_DEVICE",
    "OTB_DEVICES",
    "SYNTHETIC_DEVICE",
    "AppLogo",
    "DeviceSpec",
    "DevicePicker",
    "FeatureSelector",
    "FilterParam",
    "FilterProcessor",
    "FilterSpec",
    "Heatmap",
    "Image",
    "LinePlot",
    "DeviceParam",
    "LogPanel",
    "DeviceOption",
    "PongTask",
    "PostProcessor",
    "PredictionLabel",
    "ProcessLauncher",
    "RawSignalViewer",
    "RecordButton",
    "RecordingControls",
    "Scatter2D",
    "Scatter3D",
    "SessionManager",
    "StreamManager",
    "SignalViewer",
    "StreamPanel",
    "TemplateInspector",
    "TemplateInspectorRow",
    "TrackingTask",
    "TrialPreview",
    "ControlMapEditor",
    "VhiMovementPanel",
    "VhiStateCache",
    "VhiStateSnapshot",
    "panel_header",
    "popout_panel",
    "request_vhi_state_refresh",
    "vhi_movement_palette",
]
