# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import renderer_control_pb2 as renderer__control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in renderer_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RendererControlStub(object):
    """Control plane between MyoGestic and a renderer — a separate application that
    displays or actuates the values MyoGestic produces.

    GetControlManifest is the whole contract: it returns every control the renderer exports, by
    address (e.g. "vhi.prediction.index"), with what it can render — the kind, the range
    and the states — so neither side hard-codes a stream layout or a movement table. A
    client calls it unconditionally, once, before sending anything; there is no per-client
    negotiation and nothing to declare.

    Continuous and discrete DOFs address separate rigs — in the Virtual Hand, the
    predicted hand and the operator's control hand — so the two never contend for one
    driver. SweepControl is the verification primitive: it confirms a DOF actually
    renders the way its name claims — that a control named for a joint moves that joint,
    in the direction its name claims — without a human watching the screen.

    Continuous time-series still belongs on LSL, **one stream per DOF**: a streamed
    control's stream is named for the control's own address and is one channel wide, so
    the manifest's address is also the stream name and there is nothing further to publish
    about the transport. This service carries discrete state, low-rate continuous
    commands, and verification.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetControl = channel.unary_unary(
                '/myogestic.renderer.RendererControl/SetControl',
                request_serializer=renderer__control__pb2.SetControlRequest.SerializeToString,
                response_deserializer=renderer__control__pb2.ControlAck.FromString,
                _registered_method=True)
        self.SweepControl = channel.unary_unary(
                '/myogestic.renderer.RendererControl/SweepControl',
                request_serializer=renderer__control__pb2.SweepControlRequest.SerializeToString,
                response_deserializer=renderer__control__pb2.SweepControlReply.FromString,
                _registered_method=True)
        self.SetPresentation = channel.unary_unary(
                '/myogestic.renderer.RendererControl/SetPresentation',
                request_serializer=renderer__control__pb2.SetPresentationRequest.SerializeToString,
                response_deserializer=renderer__control__pb2.ControlAck.FromString,
                _registered_method=True)
        self.GetControlManifest = channel.unary_unary(
                '/myogestic.renderer.RendererControl/GetControlManifest',
                request_serializer=renderer__control__pb2.GetControlManifestRequest.SerializeToString,
                response_deserializer=renderer__control__pb2.ControlManifest.FromString,
                _registered_method=True)
        self.SetRecordingSession = channel.unary_unary(
                '/myogestic.renderer.RendererControl/SetRecordingSession',
                request_serializer=renderer__control__pb2.SetRecordingSessionRequest.SerializeToString,
                response_deserializer=renderer__control__pb2.RecordingAck.FromString,
                _registered_method=True)
        self.StartRecordingTrajectory = channel.unary_unary(
                '/myogestic.renderer.RendererControl/StartRecordingTrajectory',
                request_serializer=renderer__control__pb2.StartRecordingTrajectoryRequest.SerializeToString,
                response_deserializer=renderer__control__pb2.RecordingAck.FromString,
                _registered_method=True)
        self.StopRecordingTrajectory = channel.unary_unary(
                '/myogestic.renderer.RendererControl/StopRecordingTrajectory',
                request_serializer=renderer__control__pb2.StopRecordingTrajectoryRequest.SerializeToString,
                response_deserializer=renderer__control__pb2.RecordingAck.FromString,
                _registered_method=True)
        self.GetRecordingSessionState = channel.unary_unary(
                '/myogestic.renderer.RendererControl/GetRecordingSessionState',
                request_serializer=renderer__control__pb2.GetRecordingSessionStateRequest.SerializeToString,
                response_deserializer=renderer__control__pb2.RecordingSessionState.FromString,
                _registered_method=True)


class RendererControlServicer(object):
    """Control plane between MyoGestic and a renderer — a separate application that
    displays or actuates the values MyoGestic produces.

    GetControlManifest is the whole contract: it returns every control the renderer exports, by
    address (e.g. "vhi.prediction.index"), with what it can render — the kind, the range
    and the states — so neither side hard-codes a stream layout or a movement table. A
    client calls it unconditionally, once, before sending anything; there is no per-client
    negotiation and nothing to declare.

    Continuous and discrete DOFs address separate rigs — in the Virtual Hand, the
    predicted hand and the operator's control hand — so the two never contend for one
    driver. SweepControl is the verification primitive: it confirms a DOF actually
    renders the way its name claims — that a control named for a joint moves that joint,
    in the direction its name claims — without a human watching the screen.

    Continuous time-series still belongs on LSL, **one stream per DOF**: a streamed
    control's stream is named for the control's own address and is one channel wide, so
    the manifest's address is also the stream name and there is nothing further to publish
    about the transport. This service carries discrete state, low-rate continuous
    commands, and verification.
    """

    def SetControl(self, request, context):
        """Command one control frame. Intended for discrete DOFs and low-rate
        continuous updates; a per-tick continuous stream belongs on LSL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SweepControl(self, request, context):
        """Drive one DOF across its declared range and report what actually moved.
        The verification primitive: it answers "does this name render as its name
        claims, in the direction its name claims" without a human watching.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPresentation(self, request, context):
        """Configure how the renderer *presents* transitions between commanded values.
        Appearance only — see SetPresentationRequest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControlManifest(self, request, context):
        """What can this target be told to do? Returns every control the renderer exports, with
        the semantics it declares for each. Call it first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRecordingSession(self, request, context):
        """--- recording session ---------------------------------------------------
        Not control: these coordinate the renderer's participation in a recording session that
        something else owns. They live here because they drive the same rig through the
        same state machine — a second service implied an independence the renderer does
        not have, and the arbitration between them is already cross-cutting.

        Mark a recording session active or finished. While active, the renderer ignores its
        own local input so the recording has a single movement source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRecordingTrajectory(self, request, context):
        """Start cycling the control rig through a movement, so the recorded pose stream
        sweeps a continuous range instead of snapping between held states. Refused if a
        trajectory is already running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecordingTrajectory(self, request, context):
        """Stop the trajectory. Rests the rig only if one was running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecordingSessionState(self, request, context):
        """Session state, plus the movement names a trajectory may use.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RendererControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControl,
                    request_deserializer=renderer__control__pb2.SetControlRequest.FromString,
                    response_serializer=renderer__control__pb2.ControlAck.SerializeToString,
            ),
            'SweepControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SweepControl,
                    request_deserializer=renderer__control__pb2.SweepControlRequest.FromString,
                    response_serializer=renderer__control__pb2.SweepControlReply.SerializeToString,
            ),
            'SetPresentation': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPresentation,
                    request_deserializer=renderer__control__pb2.SetPresentationRequest.FromString,
                    response_serializer=renderer__control__pb2.ControlAck.SerializeToString,
            ),
            'GetControlManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControlManifest,
                    request_deserializer=renderer__control__pb2.GetControlManifestRequest.FromString,
                    response_serializer=renderer__control__pb2.ControlManifest.SerializeToString,
            ),
            'SetRecordingSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRecordingSession,
                    request_deserializer=renderer__control__pb2.SetRecordingSessionRequest.FromString,
                    response_serializer=renderer__control__pb2.RecordingAck.SerializeToString,
            ),
            'StartRecordingTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecordingTrajectory,
                    request_deserializer=renderer__control__pb2.StartRecordingTrajectoryRequest.FromString,
                    response_serializer=renderer__control__pb2.RecordingAck.SerializeToString,
            ),
            'StopRecordingTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecordingTrajectory,
                    request_deserializer=renderer__control__pb2.StopRecordingTrajectoryRequest.FromString,
                    response_serializer=renderer__control__pb2.RecordingAck.SerializeToString,
            ),
            'GetRecordingSessionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecordingSessionState,
                    request_deserializer=renderer__control__pb2.GetRecordingSessionStateRequest.FromString,
                    response_serializer=renderer__control__pb2.RecordingSessionState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myogestic.renderer.RendererControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myogestic.renderer.RendererControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RendererControl(object):
    """Control plane between MyoGestic and a renderer — a separate application that
    displays or actuates the values MyoGestic produces.

    GetControlManifest is the whole contract: it returns every control the renderer exports, by
    address (e.g. "vhi.prediction.index"), with what it can render — the kind, the range
    and the states — so neither side hard-codes a stream layout or a movement table. A
    client calls it unconditionally, once, before sending anything; there is no per-client
    negotiation and nothing to declare.

    Continuous and discrete DOFs address separate rigs — in the Virtual Hand, the
    predicted hand and the operator's control hand — so the two never contend for one
    driver. SweepControl is the verification primitive: it confirms a DOF actually
    renders the way its name claims — that a control named for a joint moves that joint,
    in the direction its name claims — without a human watching the screen.

    Continuous time-series still belongs on LSL, **one stream per DOF**: a streamed
    control's stream is named for the control's own address and is one channel wide, so
    the manifest's address is also the stream name and there is nothing further to publish
    about the transport. This service carries discrete state, low-rate continuous
    commands, and verification.
    """

    @staticmethod
    def SetControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.renderer.RendererControl/SetControl',
            renderer__control__pb2.SetControlRequest.SerializeToString,
            renderer__control__pb2.ControlAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SweepControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.renderer.RendererControl/SweepControl',
            renderer__control__pb2.SweepControlRequest.SerializeToString,
            renderer__control__pb2.SweepControlReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPresentation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.renderer.RendererControl/SetPresentation',
            renderer__control__pb2.SetPresentationRequest.SerializeToString,
            renderer__control__pb2.ControlAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControlManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.renderer.RendererControl/GetControlManifest',
            renderer__control__pb2.GetControlManifestRequest.SerializeToString,
            renderer__control__pb2.ControlManifest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRecordingSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.renderer.RendererControl/SetRecordingSession',
            renderer__control__pb2.SetRecordingSessionRequest.SerializeToString,
            renderer__control__pb2.RecordingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRecordingTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.renderer.RendererControl/StartRecordingTrajectory',
            renderer__control__pb2.StartRecordingTrajectoryRequest.SerializeToString,
            renderer__control__pb2.RecordingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRecordingTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.renderer.RendererControl/StopRecordingTrajectory',
            renderer__control__pb2.StopRecordingTrajectoryRequest.SerializeToString,
            renderer__control__pb2.RecordingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecordingSessionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.renderer.RendererControl/GetRecordingSessionState',
            renderer__control__pb2.GetRecordingSessionStateRequest.SerializeToString,
            renderer__control__pb2.RecordingSessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
