# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import myogestic_vhi_pb2 as myogestic__vhi__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in myogestic_vhi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VhiControlStub(object):
    """VENDORED COPY — do not edit here. The canonical contract lives in the
    Virtual-Hand-Interface repo at proto/myogestic_vhi.proto. Update that, copy
    it here, then run `uv run --extra grpc python tools/gen_proto.py`.

    Control plane between MyoGestic (gRPC client) and the Virtual Hand Interface
    (gRPC server, hosted in-process by the Godot app). Continuous time-series
    (predictions, hand poses) stays on LSL; this service carries only discrete
    commands. The unary return value is the ack/reject.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMovement = channel.unary_unary(
                '/myogestic.vhi.v1.VhiControl/SetMovement',
                request_serializer=myogestic__vhi__pb2.SetMovementRequest.SerializeToString,
                response_deserializer=myogestic__vhi__pb2.CommandAck.FromString,
                _registered_method=True)
        self.Freeze = channel.unary_unary(
                '/myogestic.vhi.v1.VhiControl/Freeze',
                request_serializer=myogestic__vhi__pb2.FreezeRequest.SerializeToString,
                response_deserializer=myogestic__vhi__pb2.CommandAck.FromString,
                _registered_method=True)
        self.SetSpeed = channel.unary_unary(
                '/myogestic.vhi.v1.VhiControl/SetSpeed',
                request_serializer=myogestic__vhi__pb2.SetSpeedRequest.SerializeToString,
                response_deserializer=myogestic__vhi__pb2.CommandAck.FromString,
                _registered_method=True)
        self.SetSmoothing = channel.unary_unary(
                '/myogestic.vhi.v1.VhiControl/SetSmoothing',
                request_serializer=myogestic__vhi__pb2.SetSmoothingRequest.SerializeToString,
                response_deserializer=myogestic__vhi__pb2.CommandAck.FromString,
                _registered_method=True)
        self.SetChirality = channel.unary_unary(
                '/myogestic.vhi.v1.VhiControl/SetChirality',
                request_serializer=myogestic__vhi__pb2.SetChiralityRequest.SerializeToString,
                response_deserializer=myogestic__vhi__pb2.CommandAck.FromString,
                _registered_method=True)
        self.SetSessionActive = channel.unary_unary(
                '/myogestic.vhi.v1.VhiControl/SetSessionActive',
                request_serializer=myogestic__vhi__pb2.SetSessionActiveRequest.SerializeToString,
                response_deserializer=myogestic__vhi__pb2.CommandAck.FromString,
                _registered_method=True)
        self.SetControlMode = channel.unary_unary(
                '/myogestic.vhi.v1.VhiControl/SetControlMode',
                request_serializer=myogestic__vhi__pb2.SetControlModeRequest.SerializeToString,
                response_deserializer=myogestic__vhi__pb2.CommandAck.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/myogestic.vhi.v1.VhiControl/GetState',
                request_serializer=myogestic__vhi__pb2.GetStateRequest.SerializeToString,
                response_deserializer=myogestic__vhi__pb2.StateReply.FromString,
                _registered_method=True)


class VhiControlServicer(object):
    """VENDORED COPY — do not edit here. The canonical contract lives in the
    Virtual-Hand-Interface repo at proto/myogestic_vhi.proto. Update that, copy
    it here, then run `uv run --extra grpc python tools/gen_proto.py`.

    Control plane between MyoGestic (gRPC client) and the Virtual Hand Interface
    (gRPC server, hosted in-process by the Godot app). Continuous time-series
    (predictions, hand poses) stays on LSL; this service carries only discrete
    commands. The unary return value is the ack/reject.
    """

    def SetMovement(self, request, context):
        """Select + start playing a movement on the control hand. movement_name must
        match a VHI movement (see MovementDefinitions.cs / the movements TOML) and,
        by convention, a MyoGestic class name. "Rest" returns the hand to rest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Freeze(self, request, context):
        """Freeze the control hand at its current pose, or release it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpeed(self, request, context):
        """Adjust the control-hand animation timing (the UI speed/hold/rest sliders).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSmoothing(self, request, context):
        """Toggle predicted-hand smoothing and its speed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChirality(self, request, context):
        """Set control-hand chirality (left/right mirror).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSessionActive(self, request, context):
        """Tell VHI whether a MyoGestic recording session is active. While active,
        VHI ignores local keyboard input so MyoGestic is the sole movement source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControlMode(self, request, context):
        """Set how the control hand is driven (see ControlMode) — the predefined
        movement state machine, or a continuous pose streamed over LSL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Query current VHI state. Doubles as a connection handshake and lets the
        client discover the valid movement names for the current mode.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VhiControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMovement': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMovement,
                    request_deserializer=myogestic__vhi__pb2.SetMovementRequest.FromString,
                    response_serializer=myogestic__vhi__pb2.CommandAck.SerializeToString,
            ),
            'Freeze': grpc.unary_unary_rpc_method_handler(
                    servicer.Freeze,
                    request_deserializer=myogestic__vhi__pb2.FreezeRequest.FromString,
                    response_serializer=myogestic__vhi__pb2.CommandAck.SerializeToString,
            ),
            'SetSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpeed,
                    request_deserializer=myogestic__vhi__pb2.SetSpeedRequest.FromString,
                    response_serializer=myogestic__vhi__pb2.CommandAck.SerializeToString,
            ),
            'SetSmoothing': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSmoothing,
                    request_deserializer=myogestic__vhi__pb2.SetSmoothingRequest.FromString,
                    response_serializer=myogestic__vhi__pb2.CommandAck.SerializeToString,
            ),
            'SetChirality': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChirality,
                    request_deserializer=myogestic__vhi__pb2.SetChiralityRequest.FromString,
                    response_serializer=myogestic__vhi__pb2.CommandAck.SerializeToString,
            ),
            'SetSessionActive': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSessionActive,
                    request_deserializer=myogestic__vhi__pb2.SetSessionActiveRequest.FromString,
                    response_serializer=myogestic__vhi__pb2.CommandAck.SerializeToString,
            ),
            'SetControlMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControlMode,
                    request_deserializer=myogestic__vhi__pb2.SetControlModeRequest.FromString,
                    response_serializer=myogestic__vhi__pb2.CommandAck.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=myogestic__vhi__pb2.GetStateRequest.FromString,
                    response_serializer=myogestic__vhi__pb2.StateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myogestic.vhi.v1.VhiControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myogestic.vhi.v1.VhiControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VhiControl(object):
    """VENDORED COPY — do not edit here. The canonical contract lives in the
    Virtual-Hand-Interface repo at proto/myogestic_vhi.proto. Update that, copy
    it here, then run `uv run --extra grpc python tools/gen_proto.py`.

    Control plane between MyoGestic (gRPC client) and the Virtual Hand Interface
    (gRPC server, hosted in-process by the Godot app). Continuous time-series
    (predictions, hand poses) stays on LSL; this service carries only discrete
    commands. The unary return value is the ack/reject.
    """

    @staticmethod
    def SetMovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v1.VhiControl/SetMovement',
            myogestic__vhi__pb2.SetMovementRequest.SerializeToString,
            myogestic__vhi__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Freeze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v1.VhiControl/Freeze',
            myogestic__vhi__pb2.FreezeRequest.SerializeToString,
            myogestic__vhi__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v1.VhiControl/SetSpeed',
            myogestic__vhi__pb2.SetSpeedRequest.SerializeToString,
            myogestic__vhi__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSmoothing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v1.VhiControl/SetSmoothing',
            myogestic__vhi__pb2.SetSmoothingRequest.SerializeToString,
            myogestic__vhi__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetChirality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v1.VhiControl/SetChirality',
            myogestic__vhi__pb2.SetChiralityRequest.SerializeToString,
            myogestic__vhi__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSessionActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v1.VhiControl/SetSessionActive',
            myogestic__vhi__pb2.SetSessionActiveRequest.SerializeToString,
            myogestic__vhi__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControlMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v1.VhiControl/SetControlMode',
            myogestic__vhi__pb2.SetControlModeRequest.SerializeToString,
            myogestic__vhi__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v1.VhiControl/GetState',
            myogestic__vhi__pb2.GetStateRequest.SerializeToString,
            myogestic__vhi__pb2.StateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
