# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import myogestic_vhi_v2_pb2 as myogestic__vhi__v2__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in myogestic_vhi_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VhiCanonicalControlStub(object):
    """Canonical control plane between MyoGestic and the Virtual Hand Interface.

    v1 (myogestic_vhi.proto) is untouched and still served: it speaks in *movement
    names* and in a 9-float pose whose channel meaning lives nowhere. This service
    speaks the canonical control standard instead — an application declares what it
    controls by name ("index.flexion", "hand.grasp"), and VHI answers with what it
    can render. Neither side hard-codes a channel index.

    Three things v1 could not express, and the reason this file exists:

    1. There was no handshake. A client sent nine floats and hoped. Channels 6-8
    were dead on both ends for years without anything noticing, and four
    hand-written tables in MyoGestic documented channel 1 wrongly.
    2. Pose and movements were mutually exclusive (see v1 ControlMode), so an app
    that wanted a continuous grip and a discrete grasp state needed two modes
    it could not hold at once. v2 dissolves that rather than working around it:
    continuous DOFs drive the predicted hand and discrete DOFs drive the control
    hand's movements, so the two never contend for one driver.
    3. Nothing could confirm a DOF actually renders the way its name claims.
    Verifying that VHI curls the *index* finger, in the *flexion* direction,
    required a human watching the screen. SweepControl closes that.

    Continuous time-series still belongs on LSL. This service carries the
    negotiation, discrete state, and verification.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Declare = channel.unary_unary(
                '/myogestic.vhi.v2.VhiCanonicalControl/Declare',
                request_serializer=myogestic__vhi__v2__pb2.DeclareRequest.SerializeToString,
                response_deserializer=myogestic__vhi__v2__pb2.DeclareReply.FromString,
                _registered_method=True)
        self.SetControl = channel.unary_unary(
                '/myogestic.vhi.v2.VhiCanonicalControl/SetControl',
                request_serializer=myogestic__vhi__v2__pb2.SetControlRequest.SerializeToString,
                response_deserializer=myogestic__vhi__v2__pb2.ControlAck.FromString,
                _registered_method=True)
        self.SweepControl = channel.unary_unary(
                '/myogestic.vhi.v2.VhiCanonicalControl/SweepControl',
                request_serializer=myogestic__vhi__v2__pb2.SweepControlRequest.SerializeToString,
                response_deserializer=myogestic__vhi__v2__pb2.SweepControlReply.FromString,
                _registered_method=True)


class VhiCanonicalControlServicer(object):
    """Canonical control plane between MyoGestic and the Virtual Hand Interface.

    v1 (myogestic_vhi.proto) is untouched and still served: it speaks in *movement
    names* and in a 9-float pose whose channel meaning lives nowhere. This service
    speaks the canonical control standard instead — an application declares what it
    controls by name ("index.flexion", "hand.grasp"), and VHI answers with what it
    can render. Neither side hard-codes a channel index.

    Three things v1 could not express, and the reason this file exists:

    1. There was no handshake. A client sent nine floats and hoped. Channels 6-8
    were dead on both ends for years without anything noticing, and four
    hand-written tables in MyoGestic documented channel 1 wrongly.
    2. Pose and movements were mutually exclusive (see v1 ControlMode), so an app
    that wanted a continuous grip and a discrete grasp state needed two modes
    it could not hold at once. v2 dissolves that rather than working around it:
    continuous DOFs drive the predicted hand and discrete DOFs drive the control
    hand's movements, so the two never contend for one driver.
    3. Nothing could confirm a DOF actually renders the way its name claims.
    Verifying that VHI curls the *index* finger, in the *flexion* direction,
    required a human watching the screen. SweepControl closes that.

    Continuous time-series still belongs on LSL. This service carries the
    negotiation, discrete state, and verification.
    """

    def Declare(self, request, context):
        """Negotiate a control space. The client declares every DOF it intends to
        command; VHI answers per DOF, and names the LSL layout it will read
        continuous values from. Call before streaming anything.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControl(self, request, context):
        """Command one canonical frame. Intended for discrete DOFs and low-rate
        continuous updates; a per-tick continuous stream belongs on LSL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SweepControl(self, request, context):
        """Drive one DOF across its declared range and report what actually moved.
        The verification primitive: it answers "does this name render as its name
        claims, in the direction its name claims" without a human watching.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VhiCanonicalControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Declare': grpc.unary_unary_rpc_method_handler(
                    servicer.Declare,
                    request_deserializer=myogestic__vhi__v2__pb2.DeclareRequest.FromString,
                    response_serializer=myogestic__vhi__v2__pb2.DeclareReply.SerializeToString,
            ),
            'SetControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControl,
                    request_deserializer=myogestic__vhi__v2__pb2.SetControlRequest.FromString,
                    response_serializer=myogestic__vhi__v2__pb2.ControlAck.SerializeToString,
            ),
            'SweepControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SweepControl,
                    request_deserializer=myogestic__vhi__v2__pb2.SweepControlRequest.FromString,
                    response_serializer=myogestic__vhi__v2__pb2.SweepControlReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myogestic.vhi.v2.VhiCanonicalControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myogestic.vhi.v2.VhiCanonicalControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VhiCanonicalControl(object):
    """Canonical control plane between MyoGestic and the Virtual Hand Interface.

    v1 (myogestic_vhi.proto) is untouched and still served: it speaks in *movement
    names* and in a 9-float pose whose channel meaning lives nowhere. This service
    speaks the canonical control standard instead — an application declares what it
    controls by name ("index.flexion", "hand.grasp"), and VHI answers with what it
    can render. Neither side hard-codes a channel index.

    Three things v1 could not express, and the reason this file exists:

    1. There was no handshake. A client sent nine floats and hoped. Channels 6-8
    were dead on both ends for years without anything noticing, and four
    hand-written tables in MyoGestic documented channel 1 wrongly.
    2. Pose and movements were mutually exclusive (see v1 ControlMode), so an app
    that wanted a continuous grip and a discrete grasp state needed two modes
    it could not hold at once. v2 dissolves that rather than working around it:
    continuous DOFs drive the predicted hand and discrete DOFs drive the control
    hand's movements, so the two never contend for one driver.
    3. Nothing could confirm a DOF actually renders the way its name claims.
    Verifying that VHI curls the *index* finger, in the *flexion* direction,
    required a human watching the screen. SweepControl closes that.

    Continuous time-series still belongs on LSL. This service carries the
    negotiation, discrete state, and verification.
    """

    @staticmethod
    def Declare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v2.VhiCanonicalControl/Declare',
            myogestic__vhi__v2__pb2.DeclareRequest.SerializeToString,
            myogestic__vhi__v2__pb2.DeclareReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v2.VhiCanonicalControl/SetControl',
            myogestic__vhi__v2__pb2.SetControlRequest.SerializeToString,
            myogestic__vhi__v2__pb2.ControlAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SweepControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v2.VhiCanonicalControl/SweepControl',
            myogestic__vhi__v2__pb2.SweepControlRequest.SerializeToString,
            myogestic__vhi__v2__pb2.SweepControlReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VhiTrainingAidStub(object):
    """---------------------------------------------------------------------------
    Recording / label-acquisition aid.

    Deliberately a SEPARATE service, not extra RPCs on VhiCanonicalControl, because
    the distinction is the whole point: this is not a control plane and nothing here
    is a canonical DOF.

    A canonical discrete DOF is a *held state* — an application asks for "grip" and
    the hand holds a grip. That semantics must not bend to accommodate data
    collection. But collecting regression training data needs the opposite: a
    deliberately moving control hand, so the recorded VHI_Control stream sweeps a
    continuous kinematic range for EMG windows to be aligned against.

    Both live here because both are properties of a *recording session* rather than of
    the thing being controlled:

    - the session gate, which stops VHI's local keyboard from competing with
    MyoGestic as a movement source while a session is being recorded;
    - the training program, which cycles the control hand to generate a trajectory.

    A program names a VHI movement, and that is intentional: a recording aid is
    allowed to be application-specific, precisely so the canonical vocabulary does not
    have to grow a concept ("sweep me for training") that no application controls.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRecordingSession = channel.unary_unary(
                '/myogestic.vhi.v2.VhiTrainingAid/SetRecordingSession',
                request_serializer=myogestic__vhi__v2__pb2.SetRecordingSessionRequest.SerializeToString,
                response_deserializer=myogestic__vhi__v2__pb2.TrainingAck.FromString,
                _registered_method=True)
        self.StartTrainingProgram = channel.unary_unary(
                '/myogestic.vhi.v2.VhiTrainingAid/StartTrainingProgram',
                request_serializer=myogestic__vhi__v2__pb2.StartTrainingProgramRequest.SerializeToString,
                response_deserializer=myogestic__vhi__v2__pb2.TrainingAck.FromString,
                _registered_method=True)
        self.StopTrainingProgram = channel.unary_unary(
                '/myogestic.vhi.v2.VhiTrainingAid/StopTrainingProgram',
                request_serializer=myogestic__vhi__v2__pb2.StopTrainingProgramRequest.SerializeToString,
                response_deserializer=myogestic__vhi__v2__pb2.TrainingAck.FromString,
                _registered_method=True)
        self.GetTrainingState = channel.unary_unary(
                '/myogestic.vhi.v2.VhiTrainingAid/GetTrainingState',
                request_serializer=myogestic__vhi__v2__pb2.GetTrainingStateRequest.SerializeToString,
                response_deserializer=myogestic__vhi__v2__pb2.TrainingState.FromString,
                _registered_method=True)


class VhiTrainingAidServicer(object):
    """---------------------------------------------------------------------------
    Recording / label-acquisition aid.

    Deliberately a SEPARATE service, not extra RPCs on VhiCanonicalControl, because
    the distinction is the whole point: this is not a control plane and nothing here
    is a canonical DOF.

    A canonical discrete DOF is a *held state* — an application asks for "grip" and
    the hand holds a grip. That semantics must not bend to accommodate data
    collection. But collecting regression training data needs the opposite: a
    deliberately moving control hand, so the recorded VHI_Control stream sweeps a
    continuous kinematic range for EMG windows to be aligned against.

    Both live here because both are properties of a *recording session* rather than of
    the thing being controlled:

    - the session gate, which stops VHI's local keyboard from competing with
    MyoGestic as a movement source while a session is being recorded;
    - the training program, which cycles the control hand to generate a trajectory.

    A program names a VHI movement, and that is intentional: a recording aid is
    allowed to be application-specific, precisely so the canonical vocabulary does not
    have to grow a concept ("sweep me for training") that no application controls.
    ---------------------------------------------------------------------------
    """

    def SetRecordingSession(self, request, context):
        """Mark a MyoGestic recording session active or finished. While active, VHI ignores
        its local keyboard so the recording has a single movement source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTrainingProgram(self, request, context):
        """Start cycling the control hand through a movement, producing a continuous
        trajectory on VHI_Control. Refused if a program is already running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTrainingProgram(self, request, context):
        """Stop the program and return the control hand to rest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingState(self, request, context):
        """Query the aid's state. Also carries the movement names a program may use, so a
        client can discover them without the v1 control service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VhiTrainingAidServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRecordingSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRecordingSession,
                    request_deserializer=myogestic__vhi__v2__pb2.SetRecordingSessionRequest.FromString,
                    response_serializer=myogestic__vhi__v2__pb2.TrainingAck.SerializeToString,
            ),
            'StartTrainingProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrainingProgram,
                    request_deserializer=myogestic__vhi__v2__pb2.StartTrainingProgramRequest.FromString,
                    response_serializer=myogestic__vhi__v2__pb2.TrainingAck.SerializeToString,
            ),
            'StopTrainingProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTrainingProgram,
                    request_deserializer=myogestic__vhi__v2__pb2.StopTrainingProgramRequest.FromString,
                    response_serializer=myogestic__vhi__v2__pb2.TrainingAck.SerializeToString,
            ),
            'GetTrainingState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingState,
                    request_deserializer=myogestic__vhi__v2__pb2.GetTrainingStateRequest.FromString,
                    response_serializer=myogestic__vhi__v2__pb2.TrainingState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myogestic.vhi.v2.VhiTrainingAid', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myogestic.vhi.v2.VhiTrainingAid', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VhiTrainingAid(object):
    """---------------------------------------------------------------------------
    Recording / label-acquisition aid.

    Deliberately a SEPARATE service, not extra RPCs on VhiCanonicalControl, because
    the distinction is the whole point: this is not a control plane and nothing here
    is a canonical DOF.

    A canonical discrete DOF is a *held state* — an application asks for "grip" and
    the hand holds a grip. That semantics must not bend to accommodate data
    collection. But collecting regression training data needs the opposite: a
    deliberately moving control hand, so the recorded VHI_Control stream sweeps a
    continuous kinematic range for EMG windows to be aligned against.

    Both live here because both are properties of a *recording session* rather than of
    the thing being controlled:

    - the session gate, which stops VHI's local keyboard from competing with
    MyoGestic as a movement source while a session is being recorded;
    - the training program, which cycles the control hand to generate a trajectory.

    A program names a VHI movement, and that is intentional: a recording aid is
    allowed to be application-specific, precisely so the canonical vocabulary does not
    have to grow a concept ("sweep me for training") that no application controls.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def SetRecordingSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v2.VhiTrainingAid/SetRecordingSession',
            myogestic__vhi__v2__pb2.SetRecordingSessionRequest.SerializeToString,
            myogestic__vhi__v2__pb2.TrainingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTrainingProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v2.VhiTrainingAid/StartTrainingProgram',
            myogestic__vhi__v2__pb2.StartTrainingProgramRequest.SerializeToString,
            myogestic__vhi__v2__pb2.TrainingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTrainingProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v2.VhiTrainingAid/StopTrainingProgram',
            myogestic__vhi__v2__pb2.StopTrainingProgramRequest.SerializeToString,
            myogestic__vhi__v2__pb2.TrainingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myogestic.vhi.v2.VhiTrainingAid/GetTrainingState',
            myogestic__vhi__v2__pb2.GetTrainingStateRequest.SerializeToString,
            myogestic__vhi__v2__pb2.TrainingState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
