#!/usr/bin/env python3
"""Generate a flat inventory of public classes/functions + their parameter names,
for naming-consistency cross-reference. Writes API_PARAMETERS.md at the repo root.

    uv run --extra grpc --extra serial python tools/gen_param_inventory.py
"""

from __future__ import annotations

import importlib
import inspect
from pathlib import Path

# Ordered so each symbol is listed once, under the first module that exposes it
# (the curated top-level facade first, then the subpackages that add extras).
MODULES = [
    "myogestic",
    "myogestic.sources",
    "myogestic.outputs",
    "myogestic.ml",
    "myogestic.ml.widgets",
    "myogestic.recipes.features",
    "myogestic.recipes.estimators",
    "myogestic.session",
    "myogestic.vhi.interfaces",
    "myogestic.widgets",
    "myogestic.tools.emg_generator",
]


def params(obj) -> str:
    try:
        sig = inspect.signature(obj)
    except (ValueError, TypeError):
        return "?"
    return ", ".join(n for n in sig.parameters if n not in ("self", "cls"))


def public_methods(cls):
    out = []
    for name in sorted(vars(cls)):
        if name.startswith("_"):
            continue
        m = inspect.getattr_static(cls, name)
        func = m.__func__ if isinstance(m, staticmethod | classmethod) else m
        if inspect.isfunction(func):
            out.append((name, params(func)))
        elif isinstance(m, property):
            out.append((name, "@property"))
    return out


def main() -> int:
    lines = [
        "# MyoGestic — public API parameter inventory",
        "",
        "_Auto-generated by `tools/gen_param_inventory.py` for naming cross-reference._",
        "_Names may repeat across a subpackage and the top-level facade (re-exports)._",
        "",
    ]
    seen: set[int] = set()
    for modname in MODULES:
        try:
            mod = importlib.import_module(modname)
        except Exception as e:  # noqa: BLE001
            lines.append(f"## `{modname}`  — (import failed: {e})\n")
            continue
        names = getattr(mod, "__all__", None) or [
            n for n in dir(mod) if not n.startswith("_")
        ]
        rows: list[str] = []
        for name in sorted(names):
            obj = getattr(mod, name, None)
            if obj is None or not (inspect.isclass(obj) or callable(obj)):
                continue
            # MyoGestic-defined only (drops typing/dataclasses/enum/mne_lsl/etc.)
            if not getattr(obj, "__module__", "").startswith("myogestic"):
                continue
            if id(obj) in seen:  # already listed under an earlier module
                continue
            seen.add(id(obj))
            if inspect.isclass(obj):
                rows.append(f"- **class `{name}`**(`{params(obj)}`)")
                for mname, mp in public_methods(obj):
                    rows.append(
                        f"    - `{mname}` — `{mp}`"
                        if mp != "@property"
                        else f"    - `{mname}` *(property)*"
                    )
            else:
                kind = "func" if inspect.isfunction(obj) else "callable"
                rows.append(f"- {kind} `{name}`(`{params(obj)}`)")
        if rows:
            lines.append(f"## `{modname}`")
            lines.extend(rows)
            lines.append("")
    out = Path(__file__).resolve().parent.parent / "API_PARAMETERS.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
